name: release
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Sign ${{ inputs.signed_binary_name }}
        shell: powershell
        env:
          DIGICERT_TOKEN_CFG_PATH: ${{ secrets.TEST1 }}
        run: |
          echo "v1"
          echo $env:DIGICERT_TOKEN_CFG_PATH
          echo "v2"
          echo $DIGICERT_TOKEN_CFG_PATH
